defaults:
  tenant_id: "1abc71b9-16f5-43d3-980c-346906ec0e05"
  client_id: "e22d4fff-fbbd-4ef7-ab37-e98bede1419f"
  client_secret: "XUE8Q~z21LaZMTYHgGru6IGo6J__04YzcpMu9dvr"

azure:
  endpoint: https://teamscdrmvp.documents.azure.com:443/
  key: DqzEVdCU7ei6wdtt1L1e7lw8altDMzTQTCK0TuJpmP12M9wwXGLJLdz0Knzgbe8h3uAfR4G0PwJgACDbzliVjw==
  connection_string: AccountEndpoint=https://teamscdrmvp.documents.azure.com:443/;AccountKey=DqzEVdCU7ei6wdtt1L1e7lw8altDMzTQTCK0TuJpmP12M9wwXGLJLdz0Knzgbe8h3uAfR4G0PwJgACDbzliVjw==;
  OperatorCdr:
    database_name: PstnCallRecords
    container_name: pstncdr
    partition_key: /userPrincipalName
  DRCdr:
    database_name:  DRPSTNCallRecords
    container_name: drpstncdr
    partition_key: /userPrincipalName