name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: CDRManager-ll
  PYTHON_VERSION: '3.9'
  WORKING_DIRECTORY: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip App
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        zip -r app.zip .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.zip